### ISSUE TITLE
Address list did not show up

### ISSUE THREAD

**Issue by sekisanchi** [MrLuit/EtherScamDB#1093]
Just an incident report,  on both chrome and firefox. 
https://etherscamdb.info/address/0x5208d7f63A089906889A5A9CAed81E9C889E64F8
![ethereum_scam_database](https://user-images.githubusercontent.com/1669550/42187819-69d96aa8-7e8c-11e8-8779-dd0402c3d585.jpg)

**Comment by 409H** [comment]
Addresses are usually inserted lower-case https://etherscamdb.info/address/0x5208d7f63a089906889a5a9caed81e9c889e64f8

Where did you get the link for the uppercase? I'll open an enhancement to be case-insensitive
