### ISSUE TITLE
Blacklist false positives

### ISSUE THREAD

**Issue by emiliocini** [MrLuit/EtherScamDB#1181]
The url https://etherscamdb.info/api/blacklist has a lot of false positives:

output.jsbin.com
play.google.com
huobipro.com
www.instagram.com
www.medium.com
gmail.com
twitter.com
ethonline.io
geocities.ws
user-images.githubusercontent.com
instagram.com
telegra.ph
www.huobipro.com
www.t.me
t.me
www.gmail.com
about.me
plus.google.com
docs.google.com
www.twitter.com
jsfiddle.net
etherzero.org
medium.com
www.plus.google.com
www.geocities.ws

**Comment by 409H** [comment]
Hi @emiliocini - thanks for the report. We have also come across this and should have an update out soon to address this - will ping this issue when we put it to production

**Comment by sekisanchi** [comment]
There may be some of distinct cases for the coverage of blacklisting
- Whole Root domain  
- Partiucular subdomain like Tumblr, blogger, form services
- Specific URL, Twitter short URL, open Google drive files 
- with or without www  
You should define them for other interfaces and notations also.
