### ISSUE TITLE
Proposal: Combining id, name and url fields

### ISSUE THREAD

**Issue by MrLuit** [MrLuit/EtherScamDB#1229]
In v1 the `id` and `name` fields (in scams.yaml) were introduced to allow changes to the url field without the /id/0 url breaking and to allow for non-url scams wherever needed. 

These fields have proven themselves to be quite useless, especially now that we've moved to `/domain/` pages. This means we can easily change the code to only utilise `url` fields, and drastically lower the scams.yaml filesize. One big problem is that **we don't know who's relying on these fields currently**.

## My proposal
We will both put up a banner and send an email to all API users (that we personally know of), to notify people of API changes. Wherever possible, we will create an issue or PR for open-source projects that are incompatible with the new API. 

The only breaking changes that will be made are the removal of the `id` and `name` properties for every entry in `scams.yaml`. All other properties (including `url`) will not be changed.

If a reasonable amount of API dependants are still not compatible with the changes after 2 weeks of us notifying everyone, we will delay or cancel the changes.

---------------------------

Let me know what you guys think. I'm open to other ideas/solutions.

**Comment by hahnmichaelf** [comment]
YES. FINALLY. I'm willing to help out with anyone who needs new API integration changes when we get a spec figured out :)

**Comment by MrLuit** [comment]
Please see https://medium.com/@etherscamdb/breaking-api-changes-in-v3-646217a22bac :)

Closing for now.
