### ISSUE TITLE
docs.google.com listed at API

### ISSUE THREAD

**Issue by steadramon** [MrLuit/EtherScamDB#1296]
Hi,

https://etherscamdb.info/api/blacklist/ lists docs.google.com - would adding docs.google.com to the _data/legit_urls.yaml allow the API to skip? If so I can submit a PR?

Thanks,
Paul

**Comment by 409H** [comment]
Thanks for the report. 
We should get a fix in place to check the whitelist beforehand (so a PR would work in the future) soon - currently at ETHBerlin so in the coming days
