### ISSUE TITLE
UX Improvement of "Active scams" panel  

### ISSUE THREAD

**Issue by sekisanchi** [MrLuit/EtherScamDB#144]
Scams list will be much attractive to be sorted by lines with status category, active lines group on top as default.  
Optionally, having sorted and unsorted switch by clicking the column title, and other titles also.

**Comment by 409H** [comment]
I _may_ have time do to this tomorrow if you don't @MrLuit

**Comment by MrLuit** [comment]
Just uploaded the alpha of v2, which will have new sorting options. The new version should make this much easier since all content is served dynamically.

**Comment by MrLuit** [comment]
e389ffab5922109736a223c41671f03e30bd2564 allows you to click on the column title in order to sort it that way. There are still some improvements to make to the sorting, but it works fairly good.
