### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by 409H** [MrLuit/EtherScamDB#156]
- [x] - Individual pages to finish
- [x] - Sorting to finish
- [x] - Pagination to finish
- [x] - Add the redirect page
- [x] - Update the data file 
- [x] - IP pages
- [x] - Address pages
- [x] - Update README
- [x] - Take screenshots of flagged sites.

Bugs:
- [x] - Slackbot needs to be fixed
- [x] - getCache().scams is full of duplicates, not sure why

**Comment by 409H** [comment]
> Slackbot needs to be fixed

Hey @MrLuit - what specifically is wrong with the current version?

**Comment by MrLuit** [comment]
@409H Newlines can sometimes display https://etherscan.io/address/ at the end of a report, and the 'Found in database / Not yet found in database' isn't very accurate. Using the new API that can be resolved very easily.

**Comment by 409H** [comment]
@MrLuit What is required to fulfil point "Update the data file"?

**Comment by MrLuit** [comment]
@409H Both the legit_urls.yml and the scams.yml in the v2 branch need to be copied from the master branch. That's all
