### ISSUE TITLE
Google safe browsing protection is not properly shown 

### ISSUE THREAD

**Issue by sekisanchi** [MrLuit/EtherScamDB#218]
For the URL myetherwalletverify.info, 
the summary page indicates no Google protection as shown below, 
but it's practically protected.
It should have different notation / logic / scope hopefully, to focus on high-risk address.  
   
![ethereum_scam_database](https://user-images.githubusercontent.com/1669550/31867902-0a99692a-b7d2-11e7-90c2-e1175cf4cc8a.jpg)

But by chrome,  it is captured as below  (no metamask nor etheraddresslookup)     

![security_error](https://user-images.githubusercontent.com/1669550/31867920-537143f2-b7d2-11e7-8c08-00e6ba94713e.jpg)

Firefox 

![deceptive_site_](https://user-images.githubusercontent.com/1669550/31868045-7a951ab0-b7d4-11e7-9971-e436f98959e4.jpg)

Safari 

![deceptive_website_warning](https://user-images.githubusercontent.com/1669550/31868052-a1c41e56-b7d4-11e7-8917-45f01f227df9.jpg)

Onion + metamask 

![phishing_warning](https://user-images.githubusercontent.com/1669550/31868077-e5da7c70-b7d4-11e7-8435-0fa97af523e9.jpg)

Onion 

![myetherwallet](https://user-images.githubusercontent.com/1669550/31868112-2f1817f8-b7d5-11e7-90ea-e2764062bc1b.jpg)

**Comment by MrLuit** [comment]
I just checked and I think it's caused by the `/` on the end of the url value. Haven't tested yet.
