### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by 409H** [MrLuit/EtherScamDB#228]
We need to enable CORS so that people can consume the JSON files with Javascript (specifically EtherGraphs.com is having an issue with pulling in the data with AJAX)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

We need to set a header `Access-Control-Allow-Origin: *`.

Assigning to you Luit because it might be easier to enable it in the server config.

**Comment by MrLuit** [comment]
Solved by adding the header to every API response in v2
