### ISSUE TITLE
Latest scams not being shown on the website

### ISSUE THREAD

**Issue by abcoathup** [MrLuit/EtherScamDB#580]
Scams not updated on the website.  Scams.yaml 2841 and above don't appear to be shown on the website, so the website is over a week behind the blacklist.

Reported on twitter, logging as an issue. https://twitter.com/sniko_/status/968650715957735424

**Comment by 409H** [comment]
@MrLuit Please can you take a look or grant me server access

**Comment by MrLuit** [comment]
It was some invalid yaml; fixed in 7f5aae9051708bcd6138e940d3aa51fbbc5e372f. Thanks for reporting 👍
