### ISSUE TITLE
Recent scams not showing correct MetaMask status

### ISSUE THREAD

**Issue by abcoathup** [MrLuit/EtherScamDB#585]
Recent scams e.g. tron-online.org https://etherscamdb.info/scam/2949 are not showing correct MetaMask status on the website.

Scams are included in eth-phishing-detect e.g. tron-online.org is in https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json

I assume that EtherScamDB is using the npm released version. Last npm release of eth-phishing-detect was 1.1.12, 5 months ago.  https://www.npmjs.com/package/eth-phishing-detect

**Comment by 409H** [comment]
Thanks for the report - I will schedule it in.

Just to note, I commit everything into MetaMask blacklists before they go into ESD

**Comment by 409H** [comment]
Merged in https://github.com/MrLuit/EtherScamDB/pull/623

Will put to production today
