### ISSUE TITLE
The number of active scam has been zero since yesterday. 

### ISSUE THREAD

**Issue by sekisanchi** [MrLuit/EtherScamDB#673]
Better to show some background status if it's by maintenance reason.

**Comment by 409H** [comment]
Thanks Seki, I will investigate!

**Comment by sekisanchi** [comment]
Please.  Those are valuable data, while we have handicap as open.

**Comment by 409H** [comment]
The DNS requests are timing out. I've modified the DNS server to use `1.1.1.1` that recently launched, and the same thing is happening. I'm still investigating

**Comment by 409H** [comment]
Apologies for the delay.

As of now, the issue seems to be resolved 

![image](https://user-images.githubusercontent.com/2313704/39401229-61211fbe-4b38-11e8-84e3-4ccfbc188c07.png)
