### ISSUE TITLE
(minor) Wrong addresses are shown at  #3136 

### ISSUE THREAD

**Issue by sekisanchi** [MrLuit/EtherScamDB#821]
Duplicated redundant entries are shown at Related addresses section. 
![ethereum_scam_database](https://user-images.githubusercontent.com/1669550/39908614-d6d480e8-5529-11e8-8359-57516aa9e509.jpg)

**Comment by 409H** [comment]
Thanks Seki, I'll take a look at it today

**Comment by hahnmichaelf** [comment]
This has been fixed in #949 .
