### ISSUE TITLE
Uppercase URL in Search box is not correctly processed 

### ISSUE THREAD

**Issue by sekisanchi** [MrLuit/EtherScamDB#898]
Search "ETHPAYS.ME" and "ethpays.me" did show a different result. 
Further more, input character case handling and others have to be carefully examined in the process pipeline upon variation of search string such like with or without "http://", trailing slach char etc. ,  in order to avoid false negative/positive result  for users manually accessing it. 

![ethereum_scam_database](https://user-images.githubusercontent.com/1669550/40866174-3718c8ce-6637-11e8-9b71-33a32195d010.jpg)

![ethereum_scam_database](https://user-images.githubusercontent.com/1669550/40866180-420ae83e-6637-11e8-91c7-797878dac471.jpg)

**Comment by 409H** [comment]
cc: @hahnmichaelf

**Comment by 409H** [comment]
Hi Seki, this is now fixed and on production

![image](https://user-images.githubusercontent.com/2313704/40879736-4c764074-669c-11e8-9077-0a9b29de486f.png)
