### ISSUE TITLE
The api for checking the addresses /others/ expects case sensitive argument

### ISSUE THREAD

**Issue by scsaba** [MrLuit/EtherScamDB#927]
In my opinion it should be case insensitive.

Example:

https://etherscamdb.info/api/check/0x92d43d2f55e077d1bebc6e348a9f4ff64fd4f21a/
returns
{"success":true,"result":"neutral","type":"address","entries":{}}

https://etherscamdb.info/api/check/0x92d43D2f55E077D1beBC6e348a9F4FF64fD4F21A
returns
{"success":true,"result":"blocked","type":"address","entries":[{"id":4056,"name":"blttrex.us","url":"https://blttrex.us","category":"Trust-Trading","description":"Trust-Trading site","addresses":["0x92d43D2f55E077D1beBC6e348a9F4FF64fD4F21A"],"ip":"198.252.108.77","nameservers":["ns10.hawkhost.com","ns9.hawkhost.com"],"status":"Active"}]}

The website reports the address as a scam, regardless what case is used:
https://etherscamdb.info/address/0x92d43d2f55e077d1bebc6e348a9f4ff64fd4f21a/

**Comment by 409H** [comment]
Thanks for the report - I'll get this sorted

**Comment by scsaba** [comment]
Thanks!

**Comment by 409H** [comment]
A fix for this will be pushed tomorrow 👍

**Comment by 409H** [comment]
The fix is now live - cache is updating so give it a couple minutes to properly reflect 👍

**Comment by scsaba** [comment]
That's great! Thank you for the quick fix!
