### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [MrLuit/EtherScamDB#978]
Hi @MrLuit  I am a graphics designer and open source enthusiast. I want to contribute to your good project by proposing a logo design for the project for added visibility.I have noticed it doesn't have one yet. I will be doing it as a gift for free. I need your permission before i start my design. Thanks and best regards

- tobaloidee

**Comment by hahnmichaelf** [comment]
Hey @Tobaloidee , Luit is less active on this project these days, but feel free to do this! @409H was making slow progress on icons/logos like 2 days ago for an associated project. If you do good work, I can toss a little in ETH your way for your time if you'd like it. :)

**Comment by Tobaloidee** [comment]
Surely sir..i will work on it and show you..asap

**Comment by Tobaloidee** [comment]
Hi Sir @hahnmichaelf  here is my initial desig. Please let me know if you have suggestions or modifications in mind so that i can edit. thanks!

![etherscamdb-02](https://user-images.githubusercontent.com/36028424/41388717-da97342c-6fbf-11e8-94f3-48460d7215f5.png)

logomark 
![etherscamdb-01](https://user-images.githubusercontent.com/36028424/41388722-e2637dbe-6fbf-11e8-805a-1bf213a52179.png)

logotype a



![etherscamdb-03](https://user-images.githubusercontent.com/36028424/41388734-e8adc738-6fbf-11e8-8a58-b3242a27809b.png)

logotype b



![etherscamdb-04](https://user-images.githubusercontent.com/36028424/41388738-ed25be88-6fbf-11e8-977d-3188e87270d4.png)

**Comment by Tobaloidee** [comment]
More simplified version

![etherscamdb-05](https://user-images.githubusercontent.com/36028424/41389090-7e92bf96-6fc1-11e8-9af9-cd2f8b20a273.png)

**Comment by 409H** [comment]
Oh boy I really digg this!

**Comment by Tobaloidee** [comment]
Im glad that you liked it Sir..which one is it? Ill make a PR and upload the svg files and put it also in Readme file

**Comment by hahnmichaelf** [comment]
Hey @Tobaloidee . These all look awesome! Really nice work :D. I think we like the more simplified version in your last post the best.

**Comment by Tobaloidee** [comment]
the Version 3 Sir? I will make a PR and upload the svg files

**Comment by hahnmichaelf** [comment]
Yep! And before you PR did you have any other color theme ideas for that design?

**Comment by Tobaloidee** [comment]
ill make some options sir before i make a PR..you have any color preference sir?

**Comment by hahnmichaelf** [comment]
I don't have any preferences, just wanted to see what you would come up with. It's possible that you have something in mind that we really like, and could use to change up the theme on the website

**Comment by Tobaloidee** [comment]
![etherscamdb-07](https://user-images.githubusercontent.com/36028424/41413713-7adbce1a-7016-11e8-9b77-c7bc00a31471.png)
![etherscamdb-08](https://user-images.githubusercontent.com/36028424/41413718-7ed6b282-7016-11e8-80d4-33bd204332be.png)
![etherscamdb-09](https://user-images.githubusercontent.com/36028424/41413724-812a21b8-7016-11e8-9e4b-29777b921ddf.png)
![etherscamdb-10](https://user-images.githubusercontent.com/36028424/41413730-840b177a-7016-11e8-9906-d79b8f0805c9.png)

**Comment by Tobaloidee** [comment]
There they are Sir! :)

**Comment by Tobaloidee** [comment]
in black and white

![etherscamdb-12](https://user-images.githubusercontent.com/36028424/41413980-5ddcc35e-7017-11e8-95a0-82e3acaa4468.png)
![etherscamdb-11](https://user-images.githubusercontent.com/36028424/41413985-607bd780-7017-11e8-84e6-17d5b92784bb.png)

**Comment by hahnmichaelf** [comment]
On second thought, the grey/black color scheme seems to fit most into our current website theme We're planning to make design changes in the future, but for now it is probably best to use your initial design's color idea. You can make the PR whenever you're ready! If you want you can post an ETH address, and I'll send you some ETH. It may be a few days before I can send to you because im nowhere near my funds. But i'll send to you as soon as I get home. Thanks for all your work on this sir.

**Comment by Tobaloidee** [comment]
I just made an address sir 0x0917029C59965419c0A932dfaa79650a58f89961
Ill make a PR now..Thanks so much!

**Comment by Tobaloidee** [comment]
Here's the PR #987 Sir! Thanks so much again...

**Comment by 409H** [comment]
Merged in https://github.com/MrLuit/EtherScamDB/pull/987

**Comment by MrLuit** [comment]
@Tobaloidee hey there! Could you please shoot me an email at luit@mycrypto.com? Thanks!
